Mobile version started
bekjon-me/portfolio pull request #2
Opened 2023-01-13 14:34 UTC by bekjon-me

- added header section
- added headline section

2023-01-13 14:58 UTC, NduatiKagiri requested changes
Hi @bekjon-me , 

# CHANGES REQUIRED ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so close](https://user-images.githubuser.com/87394385/212348970-ce664761-71ac-4a63-8549-12ab291e148b.gif)

## Highlights ✔️
✅ Perfect User Interface
✅ GitHub Flow observed
✅ Linters Checks are passing
✅ Good documentation

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- For HTML/CSS and HTML/CSS/JS projects, you are allowed, and it's also recommended to create folders for your assets, stylesheets, scripts, and other HTML files, but please always place your `index.html` file in the parent directory. A good reason for this is that `index` files are the entry files to your project. When running your projects, web servers will always check the index files in the parent directory, and if it is not found there, the result will be a `404 error` which means that the requested files/directories can't be found.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:58 UTC, NduatiKagiri commented on src/index.html
> +        <h1>Bekjon</h1>
- [ ] Kindly use a `a` tag for the page title/logo since it should be a link.

2023-01-13 14:58 UTC, NduatiKagiri commented on src/index.html
> +      </div>
- [ ] Good job implementing the links inside the header, but kindly wrap the hamburger with a `nav` element. Please note that in your project, the header should contain only the logo and the nav, and then nav links should contained inside the nav.

2023-01-13 14:58 UTC, NduatiKagiri commented on src/index.html
> +      <p class="subject">I’am a Software Developer</p>
- [ ] Please note that this should be a heading and not a paragraph. Kindly replace the `p` element with a heading element i.e. `hx`

2023-01-13 14:58 UTC, NduatiKagiri commented on src/index.html
> +    </section>
- [ ] Great! You have done a commendable job on this section

2023-01-13 14:58 UTC, NduatiKagiri commented on src/style.css
> +}
- [ ] Good! You have done a perfect job on your styles

2023-01-18 07:38 UTC, Olamarx approved these changes
Hi @bekjon-me,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>
## Highlights
- Linters passed ✔️
- Readme file ✔️
- Mobile version ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 08:53 UTC, merged